### PR TITLE
Some warning removals + remove unused CMake

### PR DESCRIPTION
**Pull request by kevinlul**
These should be safe to merge without changing behaviour #41

### CODE REVIEW

**Comment by edo9300** [comment]
Better use size_t to keep the code clean

**Comment by kevinlul** [comment]
https://stackoverflow.com/questions/918567/size-t-vs-containersize-type

**Comment by DyXel** [comment]
I am in favor of using `container::size_type`. However we must be consistent, either use `size_t` everywhere, or use the aforementioned type everywhere. Consistency should be top priority regardless of what type is used to solve the warnings.

**Comment by kevinlul** [comment]
Seems like there are no other instances?

**Comment by DyXel** [comment]
You didnt fix warnings disabled by this line
https://github.com/edo9300/ygopro-core/blob/d76f144199399e2512641a283aa41c2bcbf8f326/common.h#L12

I guess they can be leaved for another PR

**Comment by kevinlul** [comment]
Yeah. I left the issue open for that purpose. A ton of the warning fixes might actually change behaviour.

**Pull request merged**
